### ISSUE TITLE
Invalid options: bynmonthday, bynweekday

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-ical#39]
@Benibur hit an error when sending email invitations to an event.
Here are the server logs:
```
/usr/local/cozy/apps/calendar/node_modules/cozy-ical/node_modules/rrule/lib/rrule.js:484
        throw new Error('Invalid options: ' + invalid.join(', '))
              ^
Error: Invalid options: bynmonthday, bynweekday
    at Object.RRule (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/node_modules/rrule/lib/rrule.js:484:15)
    at VEvent.module.exports.VEvent.VEvent.build (/usr/local/cozy/apps/calendar/node_modules/cozy-ical/lib/index.js:606:15)
    at async.forEach.event.updateAttributes.attendees (/usr/local/cozy/apps/calendar/build/server/mails/mail_handler.js:95:14)
    at /usr/local/cozy/apps/calendar/node_modules/async/lib/async.js:159:20
    at /usr/local/cozy/apps/calendar/node_modules/async/lib/async.js:227:13
    at _arrayEach (/usr/local/cozy/apps/calendar/node_modules/async/lib/async.js:78:13)
    at _each (/usr/local/cozy/apps/calendar/node_modules/async/lib/async.js:69:13)
    at Object.async.forEachOf.async.eachOf (/usr/local/cozy/apps/calendar/node_modules/async/lib/async.js:226:9)
    at Object.async.forEach.async.each (/usr/local/cozy/apps/calendar/node_modules/async/lib/async.js:203:22)
    at /usr/local/cozy/apps/calendar/build/server/mails/mail_handler.js:45:18

```

**Comment by Benibur** [comment]
the chosen frequency is "every two weeks"
(put 2 for the interval)
thx for the speed !

**Comment by clochix** [comment]
See https://github.com/jkbrzt/rrule/issues/104 This error has been reported in the RRule library we use, but is still open :-S

**Comment by clochix** [comment]
I did a PR on the repository of the rrule library. If it isn't merged soon, I think we'll need to fork it and use our own fork until the problem is fixed.

**Comment by clochix** [comment]
The PR has been merged, this will be fixed once @jkbrz has published the fix on npm.

**Comment by poupotte** [comment]
@clochix any news about this issue ?

**Comment by clochix** [comment]
Unfortunately, no new stable release of [rrule](https://www.npmjs.com/package/rrule) has been published, the latest is still 2.1.0.
But there's some work in the repo, a 2.2.0-dev seems in progress. So, wait and see…

**Comment by clochix** [comment]
Once a new version of the rrule lib had been published, we'll need to revert 659dabe. Cf #46

**Comment by aenario** [comment]
If we have a working fix and rrule isnt moving fast enough, we can make an npm fork. What do you think @clochix ?
