### ISSUE TITLE
Exception when RRUle contains TZID

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-ical#40]
Found in the logs of Sync:
```
error - caldav:backend | ./build/server/backends/caldav.js:340 | Error: Unknown RRULE property ''
    at Function.RRule.parseString (/usr/local/cozy/apps/sync/node_modules/cozy-ical/node_modules/rrule/lib/rrule.js:1459:23)
    at ModelConstructor.Event.toIcal (/usr/local/cozy/apps/sync/node_modules/cozy-ical/lib/event.js:25:40)
    at CozyCalDAVBackend.module.exports.CozyCalDAVBackend._toICal (/usr/local/cozy/apps/sync/build/server/backends/caldav.js:123:17)
    at /usr/local/cozy/apps/sync/build/server/backends/caldav.js:313:26
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:232:13
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:119:25
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:24:16
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:229:17
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:516:34
    at /usr/local/cozy/apps/sync/node_modules/americano-cozy/node_modules/jugglingdb-cozy-adapter/lib/cozy_data_system.js:530:20
```

Some events (imported from Google ?) have a wrong RRule:
```
"rrule":";TZID=Europe/Warsaw:20141126T080000"
```

**Comment by poupotte** [comment]
Thanks @clochix
